#!/bin/bash

# Should use : https://github.com/tutumcloud/docker-builder

docker login

docker build -t phentz/devionic:latest devionic/.
docker push phentz/devionic:latest

#docker build -t phentz/devionic:20140304 devionic/.
#docker push phentz/devionic:20140304

docker build -t phentz/devpy:latest devpy/.
docker push phentz/devpy:latest

#docker build -t phentz/devpy:20140304 devpy/.
#docker push phentz/devpy:20140304
