#!/bin/bash
echo "Running tmux_start script ..."
#source ~/.bashrc

# Change the current directory to your working project folder
#cd /home/alan/dev/rule_the_world_project/
cd /current_dir

# ===========================================================================
# Window 1 : help
byobu-tmux \
  new-session -d -n help \; \
  send-keys "lynx /home/alan/README.html" C-m

# ===========================================================================
# Window 2 : server
# ---------------------------------------------------------------------------
# upper-left pane
byobu-tmux \
  new-window -n server \; \
  send-keys "jupyter notebook --ip=* --no-browser" C-m
# lower-left pane
byobu-tmux \
  split-window -v \; \
  send-keys "top" C-m
# lower-right pane
byobu-tmux \
  split-window -h \; \
  send-keys "/opt/web2py/web2py.py -i 0.0.0.0 -a toto -p 7999" C-m
# upper-right pane
byobu-tmux \
  select-pane -t 0 \; \
  split-window -h  \; \
  send-keys "" C-m

# ===========================================================================
# Window 3 : shells
# ---------------------------------------------------------------------------
# upper-left pane
byobu-tmux \
  new-window -n shell \; \
  send-keys "ifconfig" C-m
# lower-left pane
byobu-tmux \
  split-window -v
# lower-right pane
byobu-tmux \
  split-window -h
# upper-right pane
byobu-tmux \
  select-pane -t 0 \; \
  split-window -h

# ===========================================================================
# Window 4 : vim
# ---------------------------------------------------------------------------
# single pane
byobu-tmux \
  new-window -n vim \; \
  send-keys "vim" C-m

# ===========================================================================

# load model to couchdb
#cd couchdb && sleep 3 && couchapp push http://localhost:5984/capdemat
# load data to couchdb
#curl -d @/tmp/db.json -H "Content-type: application/json" -X POST http://127.0.0.1:5984/[mydatabase]/_bulk_docs

# Attach help window
byobu-tmux selectw -t help
byobu-tmux -2 attach-session -d
