#!/bin/sh
byobu-ctrl-a screen
# Change the current directory to your working project folder
#cd /home/alan/dev/rule_the_world_project/
cd /home/alan

#byobu-tmux new-session -d bin/notebook
byobu-tmux new-session -d "ipython notebook --ip=*"
byobu-tmux split-window -v
byobu-tmux split-window -h htop
byobu-tmux select-pane -t 0
byobu-tmux split-window -h
byobu-tmux new-window
byobu-tmux select-window -t 0

byobu-tmux -2 attach-session -d
